### ISSUE TITLE
Can't clone tables

### ISSUE THREAD

**Issue by ghinic** [Pitasi/aax-to-mp3#2]
Hey man, very excited to use your software, I am getting into an issue when cloning repo:
`Cloning into '/home/goran/aax-to-mp3/tables'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
Any ideas?

Thanks!

**Comment by pitasi** [comment]
Hi there, I see. I should have used https instead of ssh for one the submodules.

I fixed it, please try again and feel free to reopen this issue if there are any other "cloning" problems!
